### ISSUE TITLE
`template` and `repeat` + `if` attributes

### ISSUE THREAD

**Issue by mysticatea** [Polymer/TemplateBinding#194]
Code: http://jsbin.com/bogahe/1/edit

I tried to use `template if` attribute in `<td>` element.
But `<td>` element was instantiated even if the `template if` expression is `false`.
(The `<td>` instance has `if` attribute; its value is `false`.)

Is this behavior by spec?

Thanks.

**Comment by jakemac53** [comment]
This should be fixed as of https://github.com/Polymer/TemplateBinding/pull/210

**Comment by mysticatea** [comment]
Thanks a lot!
