### ISSUE TITLE
template if not working inside table

### ISSUE THREAD

**Issue by jakemac53** [Polymer/TemplateBinding#209]
See http://jsbin.com/sewisujiru/3/edit?html,output. Neither row is visible, when one should be. Interestingly if you remove the tds from inside the trs they both become visible.

**Comment by jmesserly** [comment]
pure TemplateBinding repro: http://jsbin.com/leredonusu/1/edit?html,output

it does not bootstrap correctly. bootstrap'd HTML looks like:
```html
      <template>
        <table>
          <tbody><template><tr if="{{falseItem}}"><td>Should be invisible</td></tr></template>
          <template><tr if="{{trueItem}}"><td>Should be visible</td></tr></template>
        </tbody></table>
      </template>
```

note that the "if" should be on the "template" not on the "tr".

**Comment by jakemac53** [comment]
ah, nice find :)

**Comment by mysticatea** [comment]
I guess, #194 will been fixed by this PR?

**Comment by jakemac53** [comment]
yes, I just added a note there
