### ISSUE TITLE
Spelling issue in github repository metadata

### ISSUE THREAD

**Issue by acts-human** [Polymer/TemplateBinding#219]
Currently, the github project description metadata says:

TemplateBinding **Prolyfill**

It should probably say:

TemplateBinding **Polyfill**

This issue is visible on the [project homepage](https://github.com/Polymer/TemplateBinding)

**Comment by ebidel** [comment]
That's intentional: https://twitter.com/paulvanbuuren/status/388668258460516352

**Comment by acts-human** [comment]
Lol, learn something new everyday.
